### ISSUE TITLE
Shopkeeper установка

### ISSUE THREAD

**Issue by kamuz** [andchir/shopkeeper4#1]
Судя по всему 4-й Shopkeeper теперь будет не привязан к MODX, а работать на связке Symfony и MongoDB? Это будет как отдельная CMS или что-то другое?

**Comment by andchir** [comment]
Это будет отдельно приложение, но с возможностью интеграции с CMS. Будет сделана интеграция с MODX.

**Comment by kamuz** [comment]
Круто
